//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scrips/Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Actions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Actions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Actions"",
    ""maps"": [
        {
            ""name"": ""Cubitos"",
            ""id"": ""09aa2537-4122-4de3-abf1-8a5a646aadc8"",
            ""actions"": [
                {
                    ""name"": ""Stop"",
                    ""type"": ""Button"",
                    ""id"": ""c2e21550-d92d-49c4-9e92-3a369d98f10e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""38f23f3c-87c5-4088-9a6d-8c1c1c7f2711"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Cubitos
        m_Cubitos = asset.FindActionMap("Cubitos", throwIfNotFound: true);
        m_Cubitos_Stop = m_Cubitos.FindAction("Stop", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Cubitos
    private readonly InputActionMap m_Cubitos;
    private List<ICubitosActions> m_CubitosActionsCallbackInterfaces = new List<ICubitosActions>();
    private readonly InputAction m_Cubitos_Stop;
    public struct CubitosActions
    {
        private @Actions m_Wrapper;
        public CubitosActions(@Actions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Stop => m_Wrapper.m_Cubitos_Stop;
        public InputActionMap Get() { return m_Wrapper.m_Cubitos; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CubitosActions set) { return set.Get(); }
        public void AddCallbacks(ICubitosActions instance)
        {
            if (instance == null || m_Wrapper.m_CubitosActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CubitosActionsCallbackInterfaces.Add(instance);
            @Stop.started += instance.OnStop;
            @Stop.performed += instance.OnStop;
            @Stop.canceled += instance.OnStop;
        }

        private void UnregisterCallbacks(ICubitosActions instance)
        {
            @Stop.started -= instance.OnStop;
            @Stop.performed -= instance.OnStop;
            @Stop.canceled -= instance.OnStop;
        }

        public void RemoveCallbacks(ICubitosActions instance)
        {
            if (m_Wrapper.m_CubitosActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICubitosActions instance)
        {
            foreach (var item in m_Wrapper.m_CubitosActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CubitosActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CubitosActions @Cubitos => new CubitosActions(this);
    public interface ICubitosActions
    {
        void OnStop(InputAction.CallbackContext context);
    }
}
